name: OPENWOLF
description: ""
meta_description: "Openwolf performs Medical Research Review, Public Health Innovation and Social Policy Study."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "https://openwolf.com"
google_analytics: "UA-121081752-7"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Dr Farhan Palathinkal"
# Disqus config
disqus-shortname: ""
